/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;


import java.util.Scanner;

public class App {


    public static void greeting(String[] args) {

        System.out.println("Welcome to the Brain Games!");
        Cli.name();

        private static void main (String[] args) {
            Scanner sc = new Scanner(System.in);
            System.out.println("Please enter the game number and press Enter ");
            System.out.println("1 - Greet");
            System.out.println("0 - Exit");
            System.out.print("Your choice: ");
            int number = sc.nextInt();
            if (number == 1) {
                return main();
            }
        }


    }
}
